### ISSUE TITLE
I'm curious about the webpack config "babel-loader!react-vue-style-loader"

### ISSUE THREAD

**Issue by tujoworker** [3cL1p5e7/react-vue-style-loader#1]
So, Thanks for this little package!
On my webpack config I have:

```javascript
loader: require.resolve('babel-loader'),
```

I tested out:
```javascript
{
    test: /\.(js|jsx)$/,
    include: paths.appSrc,
    loaders: [
        'react-vue-style-loader',
        {
            loader: require.resolve('babel-loader')
        },
    ]
},
```

But it seems that the <style> get's not extracted, so the result is a syntax error. 
Do You have an idea?

**Comment by 3cL1p5e7** [comment]
@tujoworker sorry for long waiting
Check this example out https://github.com/3cL1p5e7/crm.analytics/blob/crm-1/webpack.config.js
Example of using https://github.com/3cL1p5e7/crm.analytics/blob/crm-1/app/modules/calendar/calendar.jsx
Hope it helps :)

**Comment by 3cL1p5e7** [comment]
@tujoworker 
And I forgot:
You need "css-loader", "style-loader" and your custom loader, if you use, for example "postcss-loader"
